### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by surdu** [Pip3r4o/nativescript-android-utils#1]
First of all, thanks for this, should save me tons of time.

But, it looks like I have an issue building while using your plugin. Sorry if it's something obvious but I'm new to {N} and also a Java noob.

So, my code is this:

```js
com.pip3r4o.android.app.IntentService.extend("me.surdu.honkme.ActivityReconIntentService", {
	onHandleIntent: function (intent) {
		console.log("### GOT INTENT");
	}
});
```
which generates the following Java code:

```java
public class ActivityReconIntentService extends com.pip3r4o.android.app.IntentService implements com.tns.NativeScriptHashCodeProvider {
	public ActivityReconIntentService(java.lang.String param_0){
		super(param_0);
		com.tns.Runtime.initInstance(this);
	}

	public ActivityReconIntentService(){
		super();
		com.tns.Runtime.initInstance(this);
	}

	public boolean equals__super(java.lang.Object other) {
		return super.equals(other);
	}

	public int hashCode__super() {
		return super.hashCode();
	}

}
```

As you can see, it misses the `onHandleIntent` which prompts the build to fail with:

```
error: ActivityReconIntentService is not abstract and does not override abstract method onHandleIntent(Intent) in IntentService
public class ActivityReconIntentService extends com.pip3r4o.android.app.IntentService implements com.tns.NativeScriptHashCodeProvider
```

I'm using {N} v3.0.

**Comment by petekanev** [comment]
Hey @surdu! First off - apologies for tuning in some late. I was away for a bit and got out of the loop. 

The problem seems to have got something to do with the way the Android Runtime outputs static bindings. I'll investigate the possible causes and let you know when I've got more information.

**Comment by petekanev** [comment]
@surdu I found the cause for the problem. I've added more details here -> https://github.com/NativeScript/sample-android-background-services/issues/13#issuecomment-307476669

**Comment by surdu** [comment]
Thank you very much for your time ! :D
